Port = 8080
ReadTimeoutSeconds = 5
WriteTimeoutSeconds = 7
MaxHeaderBytes = 1048576
HistoryFolder = "C:/AsiCamera/History"
LogFolder = "C:/AsiCamera/Logs"
MonitorForMinutes = 1
ApiUsername = "superAdmin"
ApiKey = "superPassword"
ApiURL = "https://backend.api.server"
ApiSkipVerify = true
ApiRefreshMinutes = 10
ApiTimeoutSeconds = 10
ApiConcurrency = 1
CameraID = "camera1"
Debug = true
